//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSReader
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public int FeedID { get; set; }
        public int ChannelID { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public string Imagelink { get; set; }
        public string Date { get; set; }
    
        public virtual Channel Channel { get; set; }
    }
}
